spring:
  application:
    name: studient-ms
    description: studient microservices
    version: 1.0.0
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db-studient
    username: postgres
    password: 123456
    initialization-mode: always